### ISSUE TITLE
:sparkles: Data templating

### ISSUE THREAD

**Issue by linkdd** [linkdd/tricorder#8]
Expand **tricorder** with data specific to each host.

Example:

```
$ tricorder -i /path/to/inventory -d /path/to/data -- echo "{host_id} - {foo}"
```

Where `{host_id}` is expanded to the current host identifier and `{foo}` is expanded to the value defined in the data file.

The data file (given through the `-d` flag) is either a TOML file:

```toml
[my_host_0]

foo = "bar"

[my_host_1]

foo = "baz"
```

Or an executable producing a JSON output.

When executing the command for a specific host, **tricorder** will lookup in the data the required information to expand the command.

In the example above, the command will be expanded to:

 - `echo "my_host_0 - bar"` on `my_host_0`
 - `echo "my_host_1 - baz"` on `my_host_1`

**Comment by linkdd** [comment]
Instead of having a separate file, let's include this in the inventory:

```toml
[[hosts]]

id = "my_host_0"
address = "127.0.0.1:22"
user = "root"
tags = ["example"]

[hosts.vars]
foo = "bar"

[[hosts]]

id = "my_host_1"
address = "127.0.0.2:22"
user = "root"
tags = ["example"]

vars = { foo = "baz" }
```
